# Generated by Django 5.2.7 on 2025-10-26 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_manager",
        ),
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("user", "Пользователь"), ("manager", "Менеджер"), ("admin", "Администратор")],
                default="user",
                max_length=20,
                verbose_name="Роль",
            ),
        ),
    ]
