FROM python:3.12-slim

WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y build-essential libpq-dev postgresql-client

COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

# СНАЧАЛА копируем entrypoint
COPY deploy/entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

# ТОЛЬКО ПОТОМ копируем весь проект
COPY . .

ENTRYPOINT ["/app/entrypoint.sh"]

CMD ["gunicorn", "mailings_project.wsgi:application", "--bind", "0.0.0.0:8000"]
