# Generated by Django 5.2.8 on 2025-11-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
