# Generated by Django 5.2.7 on 2025-10-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0002_alter_mailing_options_alter_message_options_and_more"),
        ("recipients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="recipients",
            field=models.ManyToManyField(related_name="mailings", to="recipients.recipient"),
        ),
        migrations.DeleteModel(
            name="Recipient",
        ),
    ]
