# Generated by Django 5.2.7 on 2025-10-25 14:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0003_alter_mailing_recipients_delete_recipient"),
        ("recipients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("status", models.CharField(choices=[("success", "Успешно"), ("failed", "Ошибка")], max_length=20)),
                ("server_response", models.TextField(blank=True, null=True)),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="logs", to="mailings.mailing"
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="recipients.recipient"),
                ),
            ],
        ),
    ]
