# Generated by Django 5.2.7 on 2025-10-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0004_mailinglog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создана"),
                    ("launched", "Запущена"),
                    ("completed", "Завершена"),
                    ("stopped", "Остановлена"),
                ],
                default="created",
                max_length=10,
                verbose_name="Статус",
            ),
        ),
    ]
